version: '3.4'

services:
  web:
    container_name: api_service
    # image: fast_api_img
    build:
      context: . ## Current folder
      dockerfile: Dockerfile_app
      network: host
    network_mode: host
    command: uvicorn main:app --host 0.0.0.0 --port 8899
    # volumes:
    #   - ${PWD}:/code/
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=video,compute,utility
      - BROKER_URI=redis://127.0.0.1:6379
      - BACKEND_URI=redis://127.0.0.1:6379

    depends_on:
      - redis

  celery_worker:
    # image: celery_img 
    build:
      context: . ## Current folder
      dockerfile: Dockerfile_celery
      network: host

    command: celery -A celery_task_queue worker -P solo --loglevel=INFO --logfile=logs/celery.log
    volumes:
      - ${PWD}:/code/
    network_mode: host
    environment:
      - BROKER_URI=redis://127.0.0.1:6379
      - BACKEND_URI=redis://127.0.0.1:6379
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
