apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    app: api-pod
spec:
  containers:
    - name: stateless-ctn
      image: stateless_img:latest
      ports:
        - containerPort: 8000