apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: standalone-app                                  # 2
spec:                                                # 3
  containers:
    # - image: docker.io/quaden/docker_images:fast_api_img # 4
    - image: quaden/docker_images:fast_api_img # 4
      name: standalone-app                              # 5
      ports:
        - containerPort: 80                          # 6