# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.network "public_network", ip: "107.120.133.90"
    config.vm.hostname = "master.xtl"
  
    config.vm.provider "virtualbox" do |vb|
       vb.name = "master.xtl"
       vb.cpus = 4
       vb.memory = "4096"
    end

    # config.vm.provision "shell", path: "./install-docker-kube.sh"

    config.vm.provision "shell", inline: <<-SHELL
      # echo "123" | passwd --stdin root
                  echo "root:123" |  chpasswd
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
                  sed -i 's/^#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
      systemctl reload sshd
  cat >>/etc/hosts<<EOF
  107.120.133.90 master.xtl
  107.120.133.91 worker1.xtl
  107.120.133.92 worker2.xtl
  EOF
  
    SHELL
  end